config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patrons
  root 'books#index'
  resources :books do
    resources :authors
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: 'authors_books#search', as: 'search_books'
  get '/results', to: 'authors_books#results', as: 'search_results'

  get '/book_checkout', to: 'books#book_checkout', as: 'book_checkout'

  resources :checkouts do
    put 'return', on: :member
  end

  get '/overdue_books', to: 'books#overdue_books', as: 'overdue_books'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_and_belongs_to_many :books
    validates :name, presence: true
end

app/models/authors_book.rb
class AuthorsBook < ApplicationRecord
    belongs_to :author
    belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
    has_and_belongs_to_many :authors
    has_and_belongs_to_many :patrons
    has_many :checkouts
end

app/models/checkout.rb
class Checkout < ApplicationRecord
    belongs_to :book
    belongs_to :patron, foreign_key: :patron_id, class_name: 'User'
end

app/models/patron.rb
class Patron < ApplicationRecord
    has_and_belongs_to_many :books
end

app/models/user.rb
class User < ApplicationRecord
  has_many :checkouts, foreign_key: :patron_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def librarian?
    role == 'User::Librarian'
  end

  def patron?
    role == 'User::Patron'
  end
end

app/models/user/patron.rb
class User::Patron < User
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:first_name, :last_name, :role])
    end
end

app/controllers/authors_books_controller.rb
class AuthorsBooksController < ApplicationController
  def search
  end
  
    def results
      @books = Book.all
      book_ids = Book.where(["LOWER(title) LIKE ?", "%#{params[:search]}"]).ids
      @books = Book.where(id: book_ids)

      author_ids = Author.where(["LOWER(name) LIKE ?", "%#{params[:search]}"]).ids
      book_authors_ids = AuthorsBook.where(author_id: author_ids).pluck(:book_id)
      @book_authors = Book.where(id: book_authors_ids)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def create
        @book =  Book.find(params[:book_id])
        @author = @book.authors.create!(author_params)
        redirect_to book_path(@book)
      end
    
      def destroy
        @book = book.find(params[:book_authors])
        @author = @book.athors.find(params[:id])
        @author.destroy
        redirect_to book_path(@book)
      end
    
      private
        def author_params
          params.require(:author).permit(:name)
        end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    if current_user.try(:role) == 'User::Patron'
      @books = Book.where.not(id: current_user.checkouts.pluck(:book_id)) 
    else   
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_url(@book), notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @book.update(book_params)
      redirect_to book_url(@book), notice: "Book was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: "Book was successfully destroyed."
  end

  def overdue_books
    @checkouts = Checkout.where(returned: false).where('return_date < ?', Time.now)
  end

  private
    
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :language, :published, :summary, :name)
    end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
    def create
        checkout = Checkout.new(patron_id: params[:patron_id], book_id: params[:book_id], issue_date: DateTime.now.utc, return_date: Time.now) 
        if checkout.save
            redirect_to checkouts_path
        else  
            
        end
    end

    def index 
        @checkouts = Checkout.where(patron_id: current_user.id)  
    end

    def return
        @checkout = Checkout.find(params[:id])
        @checkout.update(returned: true)
        redirect_to checkouts_path
    end
    
end

app/controllers/patrons_controller.rb
class PatronsController < ApplicationController
  before_action :set_patron, only: %i[ show edit update destroy ]

  def index
    @patrons = Patron.all
  end

  def show
  end

  def new
    @patron = Patron.new
  end

  def edit
  end

  def create
    @patron = Patron.new(patron_params)

    if @patron.save
        redirect_to patron_url(@patron), notice: "Patron was successfully created." 
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @patron.update(patron_params)
      redirect_to patron_url(@patron), notice: "Patron was successfully updated." 
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @patron.destroy
    redirect_to patrons_url, notice: "Patron was successfully destroyed." 
  end

  private
    def set_patron
      @patron = Patron.find(params[:id])
    end

    def patron_params
      params.require(:patron).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_authors_helper.rb
module BookAuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/patrons_helper.rb
module PatronsHelper
end

app/views/authors/_author.html.slim
ul
    li
        = author.name
   

app/views/authors/_form.html.slim
= form_with model: [@book, @book.authors.build] do |form|
  = form.label :name
  = form.text_field :name
  = form.submit 'Enter Author'

app/views/authors_books/results.html.slim
h3 Books with   Title or Author: #{params[:search].capitalize}

ul
    - @books.each do |book|
        li    
            = link_to book.title, book_path(book)

ul
    - @book_authors.each do |book|
        li
            = link_to book.title, book_path(book)

br
= link_to 'books', books_path 

app/views/authors_books/search.html.slim
=form_with url: search_results_url, method: :get do |form|
    = form.label :search, "Search by:"
    = form.text_field :search, placeholder: 'Title or Author'
    = form.submit 'Search'
br  
= link_to 'back', books_path

app/views/books/_form.html.slim
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      h2 = "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      ul
        - @book.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :language
    = f.text_field :language
  .field
    = f.label :published
    = f.date_select :published
  .field
    = f.label :summary
    = f.text_area :summary
  .actions = f.submit

app/views/books/edit.html.slim
h1 Editing book

== render "form"

=> link_to "Show", @book
'|
=< link_to "Back", books_path

app/views/books/index.html.slim
- if user_signed_in?
  - if current_user.patron?
    h1 Available books
- else
  h1 Listing books
table
  thead
    tr
      th Title
      th
      th

  tbody
    - @books.each do |book|
      tr
        td = link_to book.title, book_path(book)
        - if user_signed_in?
          - if current_user.librarian?
            td = link_to "Edit", edit_book_path(book)
            td = link_to "Destroy", book, data: {confirm: "Are you sure?"}, method: :delete
          - if current_user.patron?
            td  = link_to "Checkout Book", checkouts_path(patron_id: current_user.id, book_id: book.id), method: :post

br
- if user_signed_in?
  - if current_user.librarian?
    = link_to "New Book", new_book_path
    '|
    = link_to "Wiew Overdue Books", overdue_books_path
  '|
  - if current_user.patron?
    => link_to 'Checkout history', checkouts_path
  '|
= link_to 'Search Book', search_books_path
'|


- if  user_signed_in? 
  = link_to 'Edit Profile', edit_user_registration_path
  '|
  = link_to 'Sign Out', destroy_user_session_path, method: :delete
- else
  = link_to 'Sign Up', new_user_registration_path
  '| 
  = link_to 'Sign In', new_user_session_path

app/views/books/new.html.slim
h1 New book

== render "form"

= link_to "Back", books_path

app/views/books/overdue_books.html.slim
h1 Overdue Books 
table
    thead 
        tr
           th Book Title
           th Issue Date
           th Return Date
           th Patron Fist Name 
           th Patron Last Name
           th Email
    tbody 
        tbody
            - @checkouts.each do |checkout|
                tr
                    td = checkout.book.title
                    td = checkout.issue_date
                    td = checkout.return_date
                    td = checkout.patron.first_name
                    td = checkout.patron.last_name
                    td = checkout.patron.email
        
            
= link_to 'books', books_path 
        

app/views/books/show.html.slim
p#notice = notice

h1 #{@book.title}

p
  strong Language:
  = @book.language

p
  strong Published:
  = @book.published
p  
  strong Authors: 
  == render @book.authors
  |
p
  strong Summary:
  = @book.summary

h3 Add authors:
== render 'authors/form'
br
- if user_signed_in?
  - if current_user.librarian?
    => link_to "Edit", edit_book_path(@book)
    '|
    = link_to "Delete Book", book_path(@book), method: :delete, data: {confirm: "Are you sure?"}
'|
=< link_to "Back", books_path

app/views/checkouts/index.html.slim
table 
    thead
        tr
            th Issue Date
            th Return Date
            th Book Title
            th Returned
            th Return Book

    tbody
        - @checkouts.each do |checkout|
            tr
                td = time_ago_in_words(checkout.issue_date)
                td = checkout.return_date
                td = checkout.book.title
                td = checkout.returned
                td = link_to 'return', return_checkout_path(checkout), { method: :put }
= link_to 'Wiew all Books', books_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibrarySystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/patrons/_form.html.slim
= form_for @patron do |f|
  - if @patron.errors.any?
    #error_explanation
      h2 = "#{pluralize(@patron.errors.count, "error")} prohibited this patron from being saved:"
      ul
        - @patron.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .actions = f.submit

app/views/patrons/edit.html.slim
h1 Editing patron

== render "form"

=> link_to "Show", @patron
'|
=< link_to "Back", patrons_path

app/views/patrons/index.html.slim
h1 Listing patrons

table
  thead
    tr
      th First name
      th Last name
      th
      th
      th

  tbody
    - @patrons.each do |patron|
      tr
        td = patron.first_name
        td = patron.last_name
        td = link_to "Show", patron
        td = link_to "Edit", edit_patron_path(patron)
        td = link_to "Destroy", patron, data: {confirm: "Are you sure?"}, method: :delete

br

= link_to "New Patron", new_patron_path

app/views/patrons/new.html.slim
h1 New patron

== render "form"

= link_to "Back", patrons_path

app/views/patrons/show.html.slim
p#notice = notice

p
  strong First name:
  = @patron.first_name

p
  strong Last name:
  = @patron.last_name

p
  strong Email:
  = @patron.email

=> link_to "Edit", edit_patron_path(@patron)
'|
=< link_to "Back", patrons_path